{% set name = "pythonnet" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b34c382905d10a371509ffafd64cae0416305c28817738a9cd138336f4e9991

build:
  number: 0
  skip: true  # [py<310 or py>=314]

requirements:
  host:
    - python
    - pip
    - setuptools >=61
    - setuptools_scm
    - wheel
    - toml
  run:
    - clr_loader >=0.2.7,<0.3.0
    - python

test:
  requires:
    - pip
    - importlib_resources
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://pythonnet.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: .Net and Mono integration for Python
  description: |
    Python for .NET is a package that gives Python programmers nearly seamless integration with the
    .NET Common Language Runtime (CLR) and provides a powerful application scripting tool for .NET
    developers.
  dev_url: https://github.com/pythonnet/pythonnet
  doc_url: https://pythonnet.github.io/pythonnet

extra:
  recipe-maintainers:
    - m-rossi
    - bgruening
    - sumit0190
