{% set name = "pythonnet" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73279c283804b9c72906fc512522d87d4c2ae1654ff3572cc8a3fc980de2891a

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}   # [not win]
    - clangdev              # [linux]
    - pkg-config            # [not win]
  host:
    - glib  # [not win]
    - mono  # [not win]
    - pip
    - pycparser
    - python
  run:
    - gettext              # [not win]
    - libiconv             # [not win]
    - mono                 # [not win]
    - python

test:
  imports:
    - clr  # [not linux]
  commands:
    - export LD_LIBRARY_PATH=${BUILD_PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/  # [linux]
    - $PYTHON -c 'import clr'  # [linux]

about:
  home: http://pythonnet.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: .Net and Mono integration for Python
  description: |
    Python for .NET is a package that gives Python programmers nearly seamless integration with the
     .NET Common Language Runtime (CLR) and provides a powerful application scripting tool for .NET
      developers.
  dev_url: https://github.com/pythonnet/pythonnet

extra:
  recipe-maintainers:
    - m-rossi
    - bgruening
