travis:
  secure:
    BINSTAR_TOKEN: Vi5tPtX1Co1Xf4zMp8kcApA45P/e5e8WIsUpmek/q+vX6R/iiX/dxKi02NRiG5tTUFv+iSR3mci36WFmTU0crj/4ibYPgApRbwqpW4/2jKESbut8k18FC8DefkOhmz4QffsyG48nIuj270aBH/5PsKCQiJa4MJkhzrll30lziszozFfjVt5ejaZ3GUVEIxxh0VujoA2kzzVZmv/dse2h5qekMaSPs7VfoIRrQe7kwP9kXRd+MN+OajiEE2fS/Dm/SiV7klcpq8y2JWrdMDX+0VVjG1kCpAaOKoKL13XStRfqDj4xbe76YkkD4w3J5cAbSHEQjQ8tsRSxoHae+OROhM1cws8WEYJJpKzl9FRKh/U4YNaOYaqsHY+jdt+nBv8XjkQ1vqwvjtRDYt8l4jZdqgtB3y+NB+X9ZM5GFok9362/84c6+FgG1yVylcaXX+jTY3W9pSbS8LDu7o9jmW/v7dGjk1gpk9NHRDFSzIQmf2rW8cdHIsrwnXtkdepvMOFfy8l7ltiby3TaW2/1mKBF/j4zaEsNdfd8BVb7XftyRfJ8jgmiG2cK3bsw7IHQpBcaR9C309sSnO+QeHBEbTiiyehM9hA17eENFcqrJ4IVt5eidAy2mkmhFaR6mhs24FPFQnP8s8G7hTiwqWlO1nY0td/0uTnSHxAoZhXB2JsYVtE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
